---
default_language_version:
  python: python3

repos:
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    name: Python-style-black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.283
  hooks:
  - id: ruff
    name: Python-check-ruff
    args: ["--fix"]
