# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[transport.ssh]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[os]
name = "debian"
version = "bullseye"

# Used by: qemu.build.py
[qemu.repository]
upstream = "https://github.com/qemu/qemu.git"
path = "{{ local.env.HOME }}/git/qemu"
tag = "v8.0.0"

# Used by: qemu.build.py
[qemu.build]
prefix = "{{ local.env.HOME }}/opt/qemu"

# Used by: the qemu.*.py scripts
[qemu]
#system_bin = "/opt/qemu/bin/qemu-system-x86_64"
system_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-system-x86_64"
img_bin = "{{ local.env.HOME }}/opt/qemu/bin/qemu-img"

#
# qemu guest (aka virtual-machines / vm / qemu-system instance)
#
# Used by:
# - qemu.guest_start.py (and qemu.guest_start_nvme.py)
# - qemu.guest_kill.py
[qemu.guest]
path = "{{ local.env.HOME }}/guests/debian-bullseye-amd64"

# Used by: qemu.guest_start.py (and qemu.guest_start_nvme.py)
[qemu.guest.system_args]
kw = {cpu = "host", smp = 4, m = "6G", accel = "kvm"}
raw = """\
 -machine type=q35,kernel_irqchip=split \
 -device intel-iommu,pt=on,intremap=on \
 -netdev user,id=n1,ipv6=off,hostfwd=tcp::4200-:22 \
 -device virtio-net-pci,netdev=n1 \
"""
# Below is another popular qemu-system argument for setting up 9p
#-virtfs fsdriver=local,id=fsdev0,security_model=mapped,mount_tag=hostshare,path={{ local.env.HOME }}/shared

# Used by: qemu.guest_init_using_image.py
[qemu.guest.init_using_image]
url = "https://refenv.fra1.digitaloceanspaces.com/boot_images/debian-bullseye-amd64.qcow2"
img = "{{ local.env.HOME }}/images/boot_images/debian-bullseye-amd64.qcow2"

# Used by: qemu.guest_init_using_cloudinit_image
[qemu.guest.init_using_cloudinit_image]
url = "https://cloud.debian.org/images/cloud/bullseye/daily/latest/debian-11-generic-amd64-daily.qcow2"
img = "{{ local.env.HOME }}/images/cloudinit/debian-11-generic-amd64-daily.qcow2"
meta = "{{ resources.auxiliary['qemu.cloudinit-debian-bullseye-meta'] }}"
user = "{{ resources.auxiliary['qemu.cloudinit-debian-bullseye-user'] }}"
#pubkey = "keys/guest_key.pub"
